#ifndef DEFS
#define DEFS
#define PI 3.14159265358979323846
#define SCREEN_WIDTH   1500
#define SCREEN_HEIGHT  800
#define PLAYER_SPEED  10
#define PLAYER_BULLET_SPEED   16
#define MAX_KEYBOARD_KEYS  350
#define SIDE_PLAYER 0
#define SIDE_ALIEN  1
#define FPS 60
#define MAX_MOUSE_BUTTONS 3 
#define ALIEN_BULLET_SPEED    8
#define MAX_STARS   500
#define MAX_SND_CHANNELS 8
#define MAX_NAME_LENGTH 1000
enum
{
    CH_ANY = -1,
    CH_PLAYER,
    CH_ALIEN_FIRE
};

enum
{
    SND_PLAYER_FIRE,
    SND_ALIEN_FIRE,
    SND_PLAYER_DIE,
    SND_ALIEN_DIE,
    SND_MAX
};

enum GameState {
    GS_MENU,
    GS_TUTORIAL,
    GS_SETTINGS,
    GS_PLAYING,
    GS_PAUSED,
    GS_EXIT
};
extern GameState gameState;

enum MovePattern {
    PATTERN_LINEAR,
    PATTERN_ZIGZAG,
    PATTERN_WAVE,
    PATTERN_SINE_VERTICAL,
    PATTERN_SPIRAL,
    PATTERN_RANDOM_DRUNK,
    PATTERN_CIRCLE
};


#endif // DEFS
